version: "3"
networks:
  front:
  back:
volumes:
  lb-data:
    external: false
  mesh-data:
    external: false
  mesh-uploads:
    external: false
  mesh-backups:
    external: false
  search-data:
    external: false
services:
  cms:
    build: ../cms
    image: gentics/mesh:1.7.0
    container_name: mesh-server
    restart: always
    volumes:
      - mesh-data:/graphdb
      - mesh-uploads:/uploads
      - mesh-backups:/backups
    environment:
      - MESH_DEFAULT_LANG=pt
      - MESH_ELASTICSEARCH_URL=http://search:9200
      - MESH_ELASTICSEARCH_START_EMBEDDED=false
      - MESH_AUTH_KEYSTORE_PASS=password
      - MESH_MONITORING_HTTP_HOST=0.0.0.0
      - MESH_ELASTICSEARCH_COMPLIANCE_MODE=ES_7
      - MESH_INITIAL_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    networks:
      - back
  search:
    build: ../search
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.5.0
    container_name: mesh-elasticsearch
    # restart: always
    volumes:
      - search-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - back
